connections/urls.py
"""Defines urls for connections."""

from django.urls import path, include

from . import views

app_name = 'connections'
urlpatterns = [
    # Connections home page.
    path('', views.connections, name='connections'),
         
    # Background process.
    path('get_connection/', views.get_connection, name='get_connection'),
    path('edit_connection/', views.edit_connection, name='edit_connection'),
    path('delete_connection/', views.delete_connection, name='delete_connection'),
    path('new_connection/', views.new_connection, name='new_connection'),
]

conversations/urls.py
"""Defines URL patterns for conversations."""

from django.urls import path

from . import views

app_name = 'conversations'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    
    # Show all conversations.
    path('conversations/', views.conversations, name='conversations'),
    
    # Create a new conversation.
    path('conversations/new/', views.new_conversation, name='new_conversation'),
    
    # Single conversation.
    path('conversations/<int:conversation_id>/', views.conversation, 
        name='conversation'),
    
    # Edit a conversation.
    path('conversations/<int:conversation_id>/edit', views.edit_conversation, 
        name='edit_conversation'),
    
    # Background processes.
    path('conversations/get_conversation/', views.get_conversation, name='get_conversation'),
    path('conversations/get_recent_messages/', views.get_recent_messages, name='get_recent_messages'),
    path('conversations/get_older_messages/', views.get_older_messages, name='get_older_messages'),
    path('conversations/submit_message/', views.submit_message, name='submit_message'),
]

shan_chat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('conversations.urls')),
    path('connections/', include('connections.urls')),
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    
    # Logout page.
    path('logout_view/', views.logout_view, name='logout_view'),
    
    # Registration page.
    path('register/', views.register, name='register'),
    
    # User settings page.
    path('settings/', views.settings, name='settings'),
    path('settings/submit_profile/', views.submit_profile, name='submit_profile'),
    path('settings/submit_password/', views.submit_password, name='submit_password'),
]

conversations/models.py
from django.db import models
from connections.models import Connection
from users.models import Profile

class Conversation(models.Model):
    """Model representing a conversation."""
    name = models.CharField(max_length=100, blank=True)
    participants = models.ManyToManyField(Profile)
    
    def __str__(self):
        """Return a string representation of the model."""
        desc = ""
        if len(self.name) > 0:
            desc += self.name + " - "
        for person in self.participants.all():
            desc += str(person) + ", "
        if len(self.participants.all()) > 0:
            desc = desc[0:-2]
        return desc

class Message(models.Model):
    """Model representing a message."""
    text = models.TextField()
    time_sent = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model."""
        time_format = "%Y/%m/%d %H:%M"
        return str(self.author) + " (" + self.time_sent.strftime(time_format) + "): " + self.text

conversations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from .models import Message, Conversation
from connections.models import Connection
from users.models import Profile

def index(request):
    """Home page for Shan-Chat."""
    # A logged-in user should never be shown the home page.
    if request.user.is_authenticated:
        return redirect('conversations:conversations')
    else:
        return render(request, 'conversations/index.html')
    
@login_required
def conversations(request):
    """Show all conversations."""
    profile = Profile.objects.filter(user=request.user)[0]
    conversations = Conversation.objects.filter(participants=profile)
    context = {"conversations": conversations}
    return render(request, 'conversations/conversations.html', context)

@login_required
def new_conversation(request):
    """Create a new conversation."""
    return render(request, 'conversations/new_conversation.html')

@login_required
def conversation(request, conversation_id):
    """Details of an individual conversation."""
    conversation = get_object_or_404(Conversation, id=conversation_id)
    participant = conversation.participants.filter(user=request.user)
    if len(participant) == 0:
        # Current user is not a participant in this conversation.
        raise Http404
        
    return render(request, 'conversations/conversation.html')

@login_required
def edit_conversation(request, conversation_id):
    """Edit a conversation."""
    conversation = get_object_or_404(Conversation, id=conversation_id)
    participant = conversation.participants.filter(user=request.user)
    if len(participant) == 0:
        # Current user is not a participant in this conversation.
        raise Http404
        
    return render(request, 'conversations/edit_conversation.html')

@login_required
@require_POST
def get_conversation(request):
    """Gets name of a conversation."""
    try:
        conversation = Conversation.objects.get(id=int(request.POST['conversationId']))
    except:
        return JsonResponse({}, status=500)
    participant = conversation.participants.filter(user=request.user)
    if len(participant) == 0:
        # Current user is not a participant in this conversation.
        return JsonResponse({}, status=404)
    
    result = { 'conversationId': conversation.id, 'name': conversation.name }
    # ADD MOST RECENT MESSAGES
    
    return JsonResponse(result)

@login_required
@require_POST
def get_recent_messages(request):
    """Gets 20 most-recent messages of a conversation."""
    try:
        conversation = Conversation.objects.get(id=int(request.POST['conversationId']))
    except:
        return JsonResponse({}, status=500)
    
    messages = Message.objects.filter(conversation=conversation).order_by(
        '-time_sent')[:20]
        
    results = []
    for message in messages:
        message_dict = { 'id': message.id,
                         'content': message.text,
                         'time_sent': message.time_sent,
                         'author_profile_id': message.author.id,
                         'author_display_name': message.author.display_name }
        results.append(message_dict)

    return JsonResponse({'messages': results})

@login_required
@require_POST
def get_older_messages(request):
    """Gets 10 most-recent messages older than the one specified by id."""
    try:
        conversation = Conversation.objects.get(id=int(request.POST['conversationId']))
        cutoff = Message.objects.get(id=int(request.POST['messageId']))
    except:
        return JsonResponse({}, status = 500)
    
    messages = Message.objects.filter(conversation=conversation).order_by('-time_sent')
    
    # Remove messages until either running out of messages
    # or the cutoff has been removed
    while(messages.count() > 0):
        check = messages[0].id == cutoff.id
        messages = messages[1:]
        if (check):
            break
    
    messages = messages[:10]
    
    results = []
    for message in messages:
        message_dict = { 'id': message.id,
                         'content': message.text,
                         'time_sent': message.time_sent,
                         'author_profile_id': message.author.id,
                         'author_display_name': message.author.display_name }
        results.append(message_dict)
    
    return JsonResponse({'messages': results})
    

@login_required
@require_POST
def submit_message(request):
    """Adds a message to the conversation."""
    try:
        conversation = Conversation.objects.get(id=int(request.POST['conversationId']))
    except:
        return JsonResponse({}, status=500)
    participant = conversation.participants.filter(user=request.user)
    if len(participant) == 0:
        # Current user is not a participant in this conversation.
        return JsonResponse({}, status=404)
    
    current_profile = Profile.objects.filter(user=request.user)[0]
    message = Message(text=request.POST['message'], author=current_profile, 
                      conversation=conversation)
    message.save()
    
    return JsonResponse({})

conversations/templates/conversations/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>Shan-Chat</title>
    {% load static %}
    <script src="{% static 'scripts/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'scripts/js.cookie.js' %}"></script>
    <script src="{% static 'scripts/base.js' %}"></script>
  </head>
  
  <body>
    <nav>
      <ul>
        <li><a href="{% url 'conversations:index' %}">Shan-Chat</a></li>
      </ul>
      {% if user.is_authenticated %}
        <ul>
          <li><a href="{% url 'conversations:conversations' %}">Conversations</a></li>
          <li><a href="{% url 'connections:connections' %}">Connections</a></li>
        </ul>
        <ul>
          <li>{{ user.username }}</li>
          <li><a href="{% url 'users:settings' %}">Settings</a></li>
          <li><a href="{% url 'users:logout_view' %}">Log Out</a></li>
        </ul>
      {% else %}
        <ul>
          <li><a href="{% url 'users:register' %}">Register</a></li>
          <li><a href="{% url 'users:login' %}">Log In</a></li>
        </ul>
      {% endif %}
    </nav>
    
    {% block header %}{% endblock header %}
    {% block content %}{% endblock content %}
    
    
  </body>

</html>

conversations/templates/conversations/conversation.html
{% extends "conversations/base.html" %}

{% block header %}
  <h1>The actual conversation</h1>
{% endblock header %}

conversations/templates/conversations/conversations.html
{% extends "conversations/base.html" %}

{% block header %}
  <h1>Your conversations.</h1>
{% endblock header %}

{% block content %}
  <div class="modal-window connection"></div>
  <div class="modal-window conversation"></div>
  <div class="modal-window conversation-settings"></div>
  
  <p><a id="new-conversation" href="{% url 'conversations:new_conversation' %}">Start a new conversation.</a></p>
  
  <ul id="conversation-list">
    {% for conversation in conversations %}
      <li>
        <a data-conversation-id="{{ conversation.id }}">{{ conversation }}</a>
      </li>
    {% empty %}
      <li>You are not a part of any conversations yet.</li>
    {% endfor %}
  </ul>
  
  {% load static %}
  <script src="{% static 'scripts/modal-window.js' %}"></script>
  <script src="{% static 'scripts/modal-conversation.js' %}"></script>
{% endblock content %}

conversations/templates/conversations/edit_conversation.html
{% extends "conversations/base.html" %}

{% block header %}
  <h1>Edit conversation.</h1>
{% endblock header %}

conversations/templates/conversations/index.html
{% extends "conversations/base.html" %}

{% block header %}
  <h1>Shan-Chat</h1>
{% endblock header %}

{% block content %}
  <p>Coming soon!</p>
{% endblock content %}

conversations/templates/conversations/new_conversation.html
{% extends "conversations/base.html" %}

{% block header %}
  <h1>New conversation.</h1>
{% endblock header %}